#!/bin/bash

#═══════════════════════════════════════════════════════════════════════════════
# WINDSURF BLACK BOX - Session Management Script
# Version: 1.0.0
# 
# Automates session lifecycle management for the Windsurf Black Box system.
# Handles session creation, logging, checkpoints, and archival.
#═══════════════════════════════════════════════════════════════════════════════

set -e

#───────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
#───────────────────────────────────────────────────────────────────────────────

# Black Box directory (relative to project root)
BLACKBOX_DIR=".windsurf-blackbox"

# Subdirectories
SESSIONS_DIR="$BLACKBOX_DIR/sessions"
CATALOG_DIR="$BLACKBOX_DIR/catalog"
ARCHIVE_DIR="$BLACKBOX_DIR/archive"
TEMPLATES_DIR="$BLACKBOX_DIR/templates"
TEMP_DIR="$BLACKBOX_DIR/.temp"

# Files
CURRENT_SESSION_FILE="$TEMP_DIR/current-session"
SESSION_LOG_FILE="$TEMP_DIR/session-log"
SEQUENCE_FILE="$BLACKBOX_DIR/.sequence"
MASTER_INDEX="$CATALOG_DIR/index.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

#───────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
#───────────────────────────────────────────────────────────────────────────────

print_header() {
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  $1${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

get_timestamp() {
    date +"%Y-%m-%d %H:%M:%S"
}

get_date() {
    date +"%Y-%m-%d"
}

get_time() {
    date +"%H:%M"
}

#───────────────────────────────────────────────────────────────────────────────
# INITIALIZATION
#───────────────────────────────────────────────────────────────────────────────

init_blackbox() {
    print_header "INITIALIZING WINDSURF BLACK BOX"
    
    # Create directory structure
    mkdir -p "$SESSIONS_DIR"
    mkdir -p "$CATALOG_DIR"
    mkdir -p "$ARCHIVE_DIR"
    mkdir -p "$TEMPLATES_DIR"
    mkdir -p "$TEMP_DIR"
    
    # Initialize sequence file if not exists
    if [ ! -f "$SEQUENCE_FILE" ]; then
        echo "0" > "$SEQUENCE_FILE"
    fi
    
    # Create master index if not exists
    if [ ! -f "$MASTER_INDEX" ]; then
        cat > "$MASTER_INDEX" << 'EOF'
# Windsurf Black Box - Session Catalog

## Quick Stats
- Total Sessions: 0
- Active Session: None
- Last Updated: Never

## Session Index

| Session ID | Date | Topic | Status | Duration |
|------------|------|-------|--------|----------|

## By Date

## By Topic

## By Status

---
*Auto-generated by Windsurf Black Box*
EOF
    fi
    
    # Create .gitignore for temp files
    cat > "$BLACKBOX_DIR/.gitignore" << 'EOF'
.temp/
*.swp
*.bak
EOF
    
    print_success "Black Box initialized at $BLACKBOX_DIR"
    echo ""
    echo "Directory structure:"
    echo "├── sessions/    - Individual session records"
    echo "├── catalog/     - Searchable indexes"
    echo "├── archive/     - Completed project archives"
    echo "├── templates/   - Document templates"
    echo "└── .temp/       - Working files (gitignored)"
}

#───────────────────────────────────────────────────────────────────────────────
# SESSION MANAGEMENT
#───────────────────────────────────────────────────────────────────────────────

generate_session_id() {
    local topic="$1"
    local today=$(get_date)
    
    # Read and increment sequence
    local seq=$(cat "$SEQUENCE_FILE" 2>/dev/null || echo "0")
    
    # Check if we need to reset sequence (new day)
    local last_date=$(head -1 "$CURRENT_SESSION_FILE" 2>/dev/null | cut -d'-' -f2-4 || echo "")
    if [ "$last_date" != "$today" ]; then
        seq=0
    fi
    
    seq=$((seq + 1))
    echo "$seq" > "$SEQUENCE_FILE"
    
    # Format sequence number with leading zeros
    local seq_formatted=$(printf "%03d" $seq)
    
    # Build session ID
    if [ -n "$topic" ]; then
        # Sanitize topic: lowercase, replace spaces with hyphens, remove special chars
        topic=$(echo "$topic" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
        echo "CONV-$today-$seq_formatted-$topic"
    else
        echo "CONV-$today-$seq_formatted"
    fi
}

start_session() {
    local topic="$1"
    local previous="$2"
    
    # Check for existing active session
    if [ -f "$CURRENT_SESSION_FILE" ]; then
        local active_session=$(cat "$CURRENT_SESSION_FILE")
        print_warning "Active session exists: $active_session"
        read -p "End it and start new? (y/N): " confirm
        if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
            end_session "Superseded by new session"
        else
            print_info "Continuing with existing session"
            return
        fi
    fi
    
    # Generate new session ID
    local session_id=$(generate_session_id "$topic")
    
    print_header "STARTING SESSION: $session_id"
    
    # Get project info
    local project_name=$(basename "$(pwd)")
    local branch=$(git branch --show-current 2>/dev/null || echo "unknown")
    local commit=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    
    # Save current session info
    echo "$session_id" > "$CURRENT_SESSION_FILE"
    
    # Initialize session log
    cat > "$SESSION_LOG_FILE" << EOF
# Session Log: $session_id

Started: $(get_timestamp)
Project: $project_name
Branch: $branch
Commit: $commit
Previous: ${previous:-None}

## Timeline

| Time | Type | Description |
|------|------|-------------|
| $(get_time) | START | Session initialized |
EOF
    
    # Create session file
    local session_file="$SESSIONS_DIR/$session_id.md"
    cat > "$session_file" << EOF
# Session Record: $session_id

## Metadata

| Field | Value |
|-------|-------|
| Session ID | $session_id |
| Date | $(get_date) |
| Started | $(get_timestamp) |
| Project | $project_name |
| Branch | $branch |
| Commit | $commit |
| Previous | ${previous:-None} |
| Status | 🟢 Active |

## Objectives

- [ ] [Define objectives at session start]

## Timeline

| Time | Type | Description |
|------|------|-------------|
| $(get_time) | START | Session initialized |

## Decisions

*No decisions recorded yet*

## Issues

*No issues recorded yet*

## Actions

*No actions recorded yet*

## Notes

*Session in progress...*

---
*Windsurf Black Box - Session Record*
*Created: $(get_timestamp)*
EOF
    
    print_success "Session started: $session_id"
    print_info "Session file: $session_file"
    echo ""
    
    # Generate Cascade start prompt
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  COPY THIS TO CASCADE:${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    cat << EOF
═══════════════════════════════════════════════════════════════
🎬 SESSION START
═══════════════════════════════════════════════════════════════

Session ID: $session_id
Project: $project_name
Branch: $branch @ $commit
Previous Session: ${previous:-None}

═══════════════════════════════════════════════════════════════
TODAY'S OBJECTIVES
═══════════════════════════════════════════════════════════════

Priority 1: [Define your main goal]
Priority 2: [Secondary goal]
Priority 3: [If time permits]

═══════════════════════════════════════════════════════════════

Please acknowledge this session ID and track all decisions,
actions, and outcomes. Reference $session_id in important moments.
EOF
    echo ""
}

log_entry() {
    local type="$1"
    local description="$2"
    local details="$3"
    
    # Verify active session
    if [ ! -f "$CURRENT_SESSION_FILE" ]; then
        print_error "No active session. Start one with: ./blackbox.sh start \"topic\""
        return 1
    fi
    
    local session_id=$(cat "$CURRENT_SESSION_FILE")
    local session_file="$SESSIONS_DIR/$session_id.md"
    local time=$(get_time)
    
    # Add to session log
    echo "| $time | $type | $description |" >> "$SESSION_LOG_FILE"
    
    # Update session file timeline
    sed -i.bak "/^| Time | Type | Description |$/a\\
| $time | $type | $description |" "$session_file" 2>/dev/null || \
    sed -i '' "/^| Time | Type | Description |$/a\\
| $time | $type | $description |" "$session_file"
    
    print_success "[$time] $type logged: $description"
    
    # If details provided, append to appropriate section
    if [ -n "$details" ]; then
        case "$type" in
            "DECISION")
                append_decision "$session_file" "$description" "$details"
                ;;
            "ISSUE")
                append_issue "$session_file" "$description" "$details"
                ;;
            "ACTION")
                append_action "$session_file" "$description" "$details"
                ;;
        esac
    fi
}

append_decision() {
    local file="$1"
    local title="$2"
    local rationale="$3"
    
    # Count existing decisions
    local count
    count=$(grep -c "^### DEC-" "$file" 2>/dev/null || true)
    count=${count:-0}
    count=$((count + 1))
    local dec_id=$(printf "DEC-%03d" $count)
    
    # Append decision
    cat >> "$file" << EOF

### $dec_id: $title
- **Choice:** $title
- **Rationale:** $rationale
- **Time:** $(get_time)
EOF
}

append_issue() {
    local file="$1"
    local problem="$2"
    local status="$3"
    
    # Count existing issues
    local count
    count=$(grep -c "^### ISS-" "$file" 2>/dev/null || true)
    count=${count:-0}
    count=$((count + 1))
    local iss_id=$(printf "ISS-%03d" $count)
    
    # Append issue
    cat >> "$file" << EOF

### $iss_id: $problem
- **Problem:** $problem
- **Status:** $status
- **Time:** $(get_time)
EOF
}

append_action() {
    local file="$1"
    local action="$2"
    local result="$3"
    
    cat >> "$file" << EOF

- **$(get_time)** $action
  - Result: $result
EOF
}

checkpoint() {
    local description="$1"
    
    if [ ! -f "$CURRENT_SESSION_FILE" ]; then
        print_error "No active session"
        return 1
    fi
    
    local session_id=$(cat "$CURRENT_SESSION_FILE")
    local branch=$(git branch --show-current 2>/dev/null || echo "unknown")
    local commit=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    local status=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    
    print_header "CHECKPOINT: $description"
    
    log_entry "CHECKPOINT" "$description" ""
    
    echo ""
    echo "State captured:"
    echo "├── Session: $session_id"
    echo "├── Branch: $branch"
    echo "├── Commit: $commit"
    echo "├── Uncommitted changes: $status files"
    echo "└── Time: $(get_timestamp)"
    
    print_success "Checkpoint created"
}

end_session() {
    local notes="$1"
    
    if [ ! -f "$CURRENT_SESSION_FILE" ]; then
        print_error "No active session to end"
        return 1
    fi
    
    local session_id=$(cat "$CURRENT_SESSION_FILE")
    local session_file="$SESSIONS_DIR/$session_id.md"
    local start_time=$(grep "Started:" "$SESSION_LOG_FILE" | cut -d' ' -f2-)
    local end_time=$(get_timestamp)
    
    print_header "ENDING SESSION: $session_id"
    
    # Calculate duration (approximate)
    local duration="[Calculate manually or enhance script]"
    
    # Log end
    log_entry "END" "Session closed" ""
    
    # Update session file
    sed -i.bak "s/| Status | 🟢 Active |/| Status | ✅ Complete |/" "$session_file" 2>/dev/null || \
    sed -i '' "s/| Status | 🟢 Active |/| Status | ✅ Complete |/" "$session_file"
    
    # Append closing info
    cat >> "$session_file" << EOF

---

## Session Closure

| Field | Value |
|-------|-------|
| Ended | $end_time |
| Duration | $duration |
| Final Branch | $(git branch --show-current 2>/dev/null || echo "unknown") |
| Final Commit | $(git rev-parse --short HEAD 2>/dev/null || echo "unknown") |

### Closing Notes
${notes:-No closing notes provided}

## Continuation Prompt

\`\`\`
SESSION CONTINUATION: $session_id
Project: $(basename "$(pwd)")
Branch: $(git branch --show-current 2>/dev/null || echo "unknown")

[Fill in from Cascade's closing summary]
\`\`\`

---
*Session closed: $end_time*
*Windsurf Black Box v1.0*
EOF
    
    # Update catalog
    update_catalog "$session_id" "complete"
    
    # Clean up temp files
    rm -f "$CURRENT_SESSION_FILE"
    rm -f "$SESSION_LOG_FILE"
    rm -f "$SESSION_LOG_FILE.bak"
    rm -f "$session_file.bak"
    
    print_success "Session ended: $session_id"
    print_info "Session file: $session_file"
    echo ""
    
    # Generate Cascade end prompt
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  COPY THIS TO CASCADE:${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    cat << EOF
═══════════════════════════════════════════════════════════════
🎬 SESSION END: $session_id
═══════════════════════════════════════════════════════════════

Please generate closing documentation:

1. SESSION SUMMARY - What was accomplished
2. STATE SNAPSHOT - Current branch/commit, build/test status
3. ACTION ITEMS - Next steps prioritized
4. CONTINUATION PROMPT - Complete prompt for resuming
5. LEARNINGS - What worked, what to improve

Format for Black Box archive at: $session_file
═══════════════════════════════════════════════════════════════
EOF
    echo ""
}

#───────────────────────────────────────────────────────────────────────────────
# CATALOG MANAGEMENT
#───────────────────────────────────────────────────────────────────────────────

update_catalog() {
    local session_id="$1"
    local status="$2"
    
    # Extract components from session ID
    local date=$(echo "$session_id" | cut -d'-' -f2-4)
    local topic=$(echo "$session_id" | cut -d'-' -f6-)
    
    # This is a simplified update - the full catalog rebuild is in rebuild_catalog
    print_info "Catalog will be rebuilt on next 'catalog' command"
}

rebuild_catalog() {
    print_header "REBUILDING SESSION CATALOG"
    
    local total=0
    local active=""
    
    # Start fresh catalog
    cat > "$MASTER_INDEX" << 'EOF'
# Windsurf Black Box - Session Catalog

EOF
    
    # Count and list all sessions
    echo "## Session Index" >> "$MASTER_INDEX"
    echo "" >> "$MASTER_INDEX"
    echo "| Session ID | Date | Topic | Status | Duration |" >> "$MASTER_INDEX"
    echo "|------------|------|-------|--------|----------|" >> "$MASTER_INDEX"
    
    for session_file in "$SESSIONS_DIR"/CONV-*.md; do
        if [ -f "$session_file" ]; then
            total=$((total + 1))
            local filename=$(basename "$session_file" .md)
            local date=$(echo "$filename" | cut -d'-' -f2-4)
            local topic=$(echo "$filename" | cut -d'-' -f6- | tr '-' ' ')
            local status=$(grep "| Status |" "$session_file" | head -1 | sed 's/.*| //' | sed 's/ |.*//')
            
            if [[ "$status" == *"Active"* ]]; then
                active="$filename"
            fi
            
            echo "| [$filename]($session_file) | $date | ${topic:-N/A} | $status | - |" >> "$MASTER_INDEX"
        fi
    done
    
    # Add quick stats at top
    local temp_file=$(mktemp)
    cat > "$temp_file" << EOF
# Windsurf Black Box - Session Catalog

## Quick Stats
- **Total Sessions:** $total
- **Active Session:** ${active:-None}
- **Last Updated:** $(get_timestamp)

EOF
    
    tail -n +3 "$MASTER_INDEX" >> "$temp_file"
    mv "$temp_file" "$MASTER_INDEX"
    
    print_success "Catalog rebuilt: $total sessions indexed"
    print_info "Catalog location: $MASTER_INDEX"
}

#───────────────────────────────────────────────────────────────────────────────
# STATUS AND INFO
#───────────────────────────────────────────────────────────────────────────────

show_status() {
    print_header "WINDSURF BLACK BOX STATUS"
    
    echo ""
    echo "📁 Black Box Location: $BLACKBOX_DIR"
    echo ""
    
    # Check for active session
    if [ -f "$CURRENT_SESSION_FILE" ]; then
        local session_id=$(cat "$CURRENT_SESSION_FILE")
        echo -e "🟢 ${GREEN}Active Session:${NC} $session_id"
        
        # Show session info
        local session_file="$SESSIONS_DIR/$session_id.md"
        if [ -f "$session_file" ]; then
            local started=$(grep "Started |" "$session_file" | head -1 | cut -d'|' -f3 | tr -d ' ')
            local branch=$(grep "Branch |" "$session_file" | head -1 | cut -d'|' -f3 | tr -d ' ')
            echo "   Started: $started"
            echo "   Branch: $branch"
        fi
    else
        echo -e "⚪ ${YELLOW}No active session${NC}"
    fi
    
    echo ""
    
    # Count sessions
    local total=$(ls -1 "$SESSIONS_DIR"/CONV-*.md 2>/dev/null | wc -l | tr -d ' ')
    echo "📊 Statistics:"
    echo "   Total sessions: $total"
    echo "   Sessions today: $(ls -1 "$SESSIONS_DIR"/CONV-$(get_date)-*.md 2>/dev/null | wc -l | tr -d ' ')"
    
    echo ""
    
    # Recent sessions
    echo "📋 Recent Sessions:"
    ls -1t "$SESSIONS_DIR"/CONV-*.md 2>/dev/null | head -5 | while read file; do
        local name=$(basename "$file" .md)
        local status=$(grep "| Status |" "$file" | head -1 | sed 's/.*| //' | sed 's/ |.*//')
        echo "   $status $name"
    done
    
    echo ""
}

#───────────────────────────────────────────────────────────────────────────────
# SEARCH
#───────────────────────────────────────────────────────────────────────────────

search_sessions() {
    local query="$1"
    
    print_header "SEARCHING: $query"
    
    echo ""
    echo "Matching sessions:"
    echo ""
    
    grep -l -r "$query" "$SESSIONS_DIR"/*.md 2>/dev/null | while read file; do
        local name=$(basename "$file" .md)
        local matches=$(grep -c "$query" "$file")
        echo "  📄 $name ($matches matches)"
        grep -n "$query" "$file" | head -3 | while read line; do
            echo "     └─ $line"
        done
    done
    
    echo ""
}

#───────────────────────────────────────────────────────────────────────────────
# HELP
#───────────────────────────────────────────────────────────────────────────────

show_help() {
    cat << 'EOF'
═══════════════════════════════════════════════════════════════
  WINDSURF BLACK BOX - Command Reference
═══════════════════════════════════════════════════════════════

USAGE:
  ./blackbox.sh <command> [arguments]

COMMANDS:
  Session Management:
    init                    Initialize Black Box in current project
    start <topic>           Start new session with optional topic
    end [notes]             End current session
    status                  Show current status
    
  Logging (during active session):
    action <desc> [result]  Log an action
    decision <desc> <why>   Log a decision with rationale
    issue <desc> [status]   Log an issue
    checkpoint <desc>       Create a checkpoint
    milestone <desc>        Mark a milestone
    note <text>             Add a note
    
  Catalog:
    catalog                 Rebuild session catalog
    search <query>          Search all sessions
    list [n]                List recent sessions (default: 10)
    
  Utilities:
    id [topic]              Generate session ID without starting
    export <session-id>     Export session to standalone file
    archive <project>       Archive all sessions for a project

EXAMPLES:
  ./blackbox.sh init
  ./blackbox.sh start "user-authentication"
  ./blackbox.sh action "Implemented login flow" "success"
  ./blackbox.sh decision "Use JWT tokens" "Stateless, scalable"
  ./blackbox.sh checkpoint "Before refactoring auth"
  ./blackbox.sh end "Completed auth, ready for testing"
  ./blackbox.sh search "authentication"

QUICK START:
  1. ./blackbox.sh init          # One-time setup
  2. ./blackbox.sh start "task"  # Begin session
  3. ... do work, log as needed ...
  4. ./blackbox.sh end           # Close session

═══════════════════════════════════════════════════════════════
EOF
}

#───────────────────────────────────────────────────────────────────────────────
# MAIN COMMAND ROUTER
#───────────────────────────────────────────────────────────────────────────────

main() {
    local command="$1"
    shift
    
    case "$command" in
        # Initialization
        init)
            init_blackbox
            ;;
        
        # Session management
        start)
            start_session "$1" "$2"
            ;;
        end)
            end_session "$*"
            ;;
        status|stat|s)
            show_status
            ;;
        
        # Logging
        action|a)
            log_entry "ACTION" "$1" "$2"
            ;;
        decision|d)
            log_entry "DECISION" "$1" "$2"
            ;;
        issue|i)
            log_entry "ISSUE" "$1" "$2"
            ;;
        checkpoint|cp)
            checkpoint "$1"
            ;;
        milestone|m)
            log_entry "MILESTONE" "$1" ""
            ;;
        note|n)
            log_entry "NOTE" "$*" ""
            ;;
        
        # Catalog
        catalog|cat)
            rebuild_catalog
            ;;
        search)
            search_sessions "$1"
            ;;
        list|ls)
            ls -1t "$SESSIONS_DIR"/CONV-*.md 2>/dev/null | head -${1:-10} | while read f; do
                echo "  $(basename "$f" .md)"
            done
            ;;
        
        # Utilities
        id)
            generate_session_id "$1"
            ;;
        
        # Help
        help|--help|-h|"")
            show_help
            ;;
        
        *)
            print_error "Unknown command: $command"
            echo "Run './blackbox.sh help' for usage information"
            exit 1
            ;;
    esac
}

# Run main with all arguments
main "$@"
